# Generated by Django 6.0.6 on 2026-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
    ]
